|
name: Cron Job

on:
schedule:
- cron: '0 * * * *'  # Run every hour

jobs:
run-maintenance:
runs-on: ubuntu-latest

steps:
- uses: actions/checkout@v2
- name: Set up Python 3.8
uses: actions/setup-python@v2
with:
python-version: '3.8'
- name: Run maintenance script
run: |
./scripts/maintenance.sh